#!/bin/bash

# =============================================================================
# Script:   csc_choices.sh
# Purpose:  Generates the install_choices.xml file on the macOS endpoint
#           that defines which Cisco Secure Client modules are selected for
#           installation when the package installer is executed by the
#           Install Script (csc_install.sh).
#
# Overview:
#   This script writes an install_choices.xml file to the endpoint that
#   controls the module selection behavior of the Cisco Secure Client
#   package installer. When the Install Script invokes the macOS installer
#   command with the -applyChoiceChangesXML flag, the installer reads this
#   file and installs only the modules whose selected attribute is set to
#   1, overriding the package defaults.
#
#   The choices file generated by this script is configured for a
#   deployment of the VPN, Umbrella, ZTA, and Duo Desktop modules, which
#   are the modules supported by the tamper resistance framework described
#   in the guide. The Duo Desktop component (choice_duo) is included as
#   a required dependency of the ZTA module. The UI component (choice_ui)
#   is also enabled. All other modules are deselected by default.
#
#   The module selection values embedded in this script must be reviewed
#   and adjusted to reflect the specific modules licensed and required in
#   your environment before deployment. Any module not covered by your
#   Cisco Secure Access subscription or not required by your security
#   policy should have its selected attribute set to 0. Any additional
#   modules required in your environment, such as DART, ISE Posture, or
#   NVM, must have their selected attribute updated to 1 before
#   deployment.
#
#   NOTE: When enabling the ZTA module (choice_zta), the Duo Desktop
#   component (choice_duo) must also be set to 1. Enabling choice_zta
#   without enabling choice_duo will result in an incomplete ZTA
#   installation.
#
#   On execution, the script first creates the target directory if it
#   does not already exist, then writes the complete install_choices.xml
#   file to the defined path. It validates the exit code of each
#   operation and exits with an error if either step fails.
#
#   This script is intended to be configured as the Before script in the
#   Jamf Pro installation policy alongside the Install Script
#   (csc_install.sh), ensuring the choices file is present on disk before
#   the installer is invoked. It must execute successfully before
#   csc_install.sh runs.
#
# Usage:
#   Deployed via Jamf Pro policy as the Before script. To invoke the
#   associated policy manually on a managed device:
#     sudo jamf policy -event <custom_event_trigger>
#
#   Example:
#     sudo jamf policy -event csc_install
#
# Parameters:
#   None. All configuration values are defined as variables within the
#   script.
#
# Configuration:
#   The following variables and module selection values must be reviewed
#   and updated to match your environment before deployment:
#
#   choicesDir  - The directory in which the install_choices.xml file is
#                 written. Defaults to:
#                   /Library/Application Support/SecureClientEnforcement
#                 This path is consistent with the shared state directory
#                 used by the broader enforcement framework. This value
#                 should only be changed if your environment requires a
#                 different path, and must be updated consistently in both
#                 this script and csc_install.sh if changed.
#
#   choicesFile - The full path to the generated choices file. Derived
#                 from choicesDir and the fixed filename
#                 install_choices.xml. Must exactly match the path
#                 referenced in csc_install.sh. If the path differs
#                 between the two scripts, the installer will not find
#                 the choices file and will proceed using the package
#                 defaults.
#
#   Module selected attribute values:
#                 For each choiceIdentifier entry in the generated XML,
#                 the selected attribute determines whether that module
#                 will be installed. Set the attributeSetting value to:
#                   <integer>1</integer>  to include the module
#                   <integer>0</integer>  to exclude the module
#
#                 The current default selection state for each module is:
#                   choice_anyconnect_vpn        1 (enabled)
#                   choice_dart                  0 (disabled)
#                   choice_secure_firewall_      0 (disabled)
#                     posture
#                   choice_iseposture            0 (disabled)
#                   choice_nvm                   0 (disabled)
#                   choice_secure_umbrella       1 (enabled)
#                   choice_thousandeyes          0 (disabled)
#                   choice_duo                   1 (enabled –
#                                                  required by ZTA)
#                   choice_zta                   1 (enabled)
#                   choice_ui                    1 (enabled)
#
#                 Review and adjust these values to reflect the modules
#                 licensed and required in your environment before
#                 deployment.
#
# Requirements:
#   - Script must be configured as the Before script in the same Jamf
#     Pro policy as csc_install.sh, and must complete successfully
#     before csc_install.sh runs.
#   - Script must be executed in the root context, as is the case when
#     run via a Jamf Pro policy.
# =============================================================================

choicesDir="/Library/Application Support/SecureClientEnforcement"
choicesFile="${choicesDir}/install_choices.xml"

# Make Simple File
MAKEDIR()
{
    if [ ! -d "$choicesDir" ]; then
        echo "Creating directory: $choicesDir"
        mkdir -p "$choicesDir"
        if [ $? -ne 0 ]; then
            echo "ERROR: Failed to create directory: $choicesDir"
            exit 1
        fi
    else
        echo "Directory already exists: $choicesDir"
    fi
}

# Create install_choices.xml
MAKEXML()
{
    echo "Creating install_choices.xml at: $choicesFile"
    cat > "$choicesFile" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_anyconnect_vpn</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_anyconnect_vpn</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>0</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_anyconnect_vpn</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_dart</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_dart</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>0</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_dart</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_secure_firewall_posture</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_secure_firewall_posture</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>0</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_secure_firewall_posture</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_iseposture</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_iseposture</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>0</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_iseposture</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_nvm</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_nvm</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>0</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_nvm</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_secure_umbrella</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_secure_umbrella</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>1</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_secure_umbrella</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_thousandeyes</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_thousandeyes</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>0</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_thousandeyes</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_duo</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_duo</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>1</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_duo</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<true/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_zta</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_zta</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>1</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_zta</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>visible</string>
		<key>choiceIdentifier</key>
		<string>choice_ui</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<false/>
		<key>choiceAttribute</key>
		<string>enabled</string>
		<key>choiceIdentifier</key>
		<string>choice_ui</string>
	</dict>
	<dict>
		<key>attributeSetting</key>
		<integer>1</integer>
		<key>choiceAttribute</key>
		<string>selected</string>
		<key>choiceIdentifier</key>
		<string>choice_ui</string>
	</dict>
</array>
</plist>
EOF

    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to create file: $choicesFile"
        exit 1
    else
        echo "Successfully created: $choicesFile"
    fi
}

# Main Process

MAKEDIR
MAKEXML
